CREATE TABLE IF NOT EXISTS publications (
    id SERIAL PRIMARY KEY,
    author_id INTEGER REFERENCES authors(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    year INTEGER,
    link TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
